version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: vk-hackaton-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6432:6432"